# Makefile
TOP = ..
include $(TOP)/configure/CONFIG

HTMLS_DIR = .
HTMLS += tyGSOctal.html
HTMLS += tyGSOctalRelease.html

SRCS += tyGSOctal.c

OBJS_vxWorks += tyGSOctal.o

include $(TOP)/configure/RULES
