# Makefile.Host
TOP = ../..
include $(TOP)/config/CONFIG_APP

DBDINSTALL += drvIpac.dbd

INC += drvIpac.h

HTMLS_DIR = .
HTMLS += index.html
HTMLS += logo101.gif
HTMLS += drvIpac.html
HTMLS += ipacRelease.html

include $(TOP)/config/RULES.Host
